version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: resume-db
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resume_user -d resume_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 